site_name: IMAU Python for Lunch
# site_url: https://mydomain.org/mysite
theme:
  name: material

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

plugins:
  - mkdocs-jupyter:
      ignore_h1_titles: True
