site_name: IMAU Python for Lunch
site_url: https://uu-imau.github.io/python-for-lunch/
repo_url: https://github.com/UU-IMAU/python-for-lunch
edit_uri: edit/main/docs/
theme:
    name: zensical
    logo: assets/logo.png
    favicon: assets/logo.png
    features:
        - content.action.edit
    palette:
        primary: green
        accent: green

markdown_extensions:
    - admonition
    - attr_list
    - pymdownx.details
    - pymdownx.superfences
    - pymdownx.emoji:
          emoji_index: !!python/name:material.extensions.emoji.twemoji
          emoji_generator: !!python/name:material.extensions.emoji.to_svg

nav:
    - index.md
    - talks/index.md
    - contributing.md
    - resources.md
plugins:
    - mkdocs-jupyter:
          ignore_h1_titles: True
