site_name: IMAU Python for Lunch
site_url: https://uu-imau.github.io/python-for-lunch/
repo_url: https://github.com/UU-IMAU/python-for-lunch
theme:
  name: material

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

plugins:
  - mkdocs-jupyter:
      ignore_h1_titles: True
